---
title: "Basics of Python for Data Science"
subtitle: "PhD Course in Psychological Sciences - University of Padova"
author: "Enrico Toffalini"
include-in-header: assets/header.html
format: 
  html:
    self-contained: true
    toc: true   
    toc-depth: 3 
    toc-expand: 3 
    code-fold: false 
    message: false
    css: "assets/custom.css"
editor: visual
---

```{r, echo=F, include=F}
reticulate::repl_python()
```

## About This Course

This is a short (10 hours) introductory course on <a href="https://www.python.org/" target=_blank>**Python**</a> that is offered within the <a href="https://dottorato.psy.unipd.it/en" target="_blank">PhD program in Psychological Sciences</a> *(University of Padova)*. R is more extensively used for statistical analysis and data science in this PhD program, but familiarity with Python is useful for different purposes, including advanced machine learning applications, deep learning models, natural language processing, computational efficiency in some scenarios, and programming experiments. Also, Python is widely required in industry and business, so basic proficiency with it a valuable asset! No prerequisites, but having attended <a href="https://enricotoffalini.github.io/Basics-R/" target="_blank">*Basics of R for Data Science*</a> may greatly help (well, it is a mandatory course for our PhD students)

You are encouraged to look at this online book available on GitHub: <a href="https://jakevdp.github.io/PythonDataScienceHandbook//" target="_blank">***Python Data Science Handbook***</a>

## Dates and Rooms 2025

| Day                 | Time        | Room |
|---------------------|-------------|------|
| Tuesday, June 3rd   | 09:00-11:30 | 4R   |
| Wednesday, June 4th | 09:00-11:30 | 4R   |
| Thursday, June 5th  | 09:00-11:30 | 4S   |
| Friday, June 6th    | 09:00-11:30 | 4S   |

## Getting Started

Bookmark this course homepage to have a quick access to this material (<a href="https://enricotoffalini.github.io/Basics-Python/">https://enricotoffalini.github.io/Basics-Python/</a>). Then do this:

1.  **Install Python**: go to the official <a href="https://www.python.org/downloads/" target="_blank">Python download page</a> and follow the installation instructions for your operating system.
2.  **Install an IDE** *(Integrated Development Environment)*: Suggested IDEs are <a href="https://posit.co/download/rstudio-desktop/" target="_blank">Posit/**RStudio**</a> (which you should have already installed for the other courses; it also supports Python!) or <a href="https://www.spyder-ide.org/" target="_blank">**Spyder**</a>.
3.  **Test your local setup**: Make sure that your Python installation works; open your IDE of choice and run the following code in the console:

```{python, eval=F}
!pip install numpy # install package "numpy" from inside IDE

import numpy as np
np.random.normal(0,1,size=10)
```

If you get any errors when running the first line, try install the package via terminal with <br/> `pip install numpy`

4.  **Take a look at** <a href="https://colab.research.google.com/" target="_blank">Colab</a>: Some basic practice and exercises will be conducted on <a href="https://colab.research.google.com/" target="_blank">**Google Colab**</a> (you need to log in with a Google account), a free online environment for writing and running Python in the browser without any local installation.

## Course Topics

##### Getting Started with Python: Environment, Syntax, Tools

An introduction to Python and its ecosystem: setting up Python locally or in the cloud (*Google Colab*), using *IDE*s, understanding basic syntax and operations, creating and naming variables, using packages and functions, and working with core data structures (*lists*, *tuples*, *dictionaries*) and indexing.

##### Basics of Programming in Python

A hands-on to basic programming concepts such as conditional logic, loops, and write and use custom functions. These are core skills for writing flexible and efficient Python code.

##### Entering the World of Data Science in Python: `pandas`, `numpy`, and more

Explore the Python core libraries for data science. We will learn how to manipulate and analyze tabular data with `pandas`, handle arrays and numerical operations with `numpy`, and get a taste of statistical modeling and basic machine learning using `statsmodels` and `scikit-learn`.

##### A Bit on Fancy Topics?

Depending on interest, we may explore more advanced topics such as data visualization, basic machine learning, and use of deep learning and language models available via <a href="https://huggingface.co/" target="_blank">HuggingFace</a> 🤗, or even simple experiment programming. After all, that's truly why we want to use Python.

## Materials

### Slides *(in progress!)*

-   [**Intro to This Course, aka Why We Should Use Python**](Slides/00.IntroPython.html){target="_blank"}
-   [**Getting Started: IDEs, Operations, Basic Types of Data**](Slides/01.GettingStartedPython.html){target="_blank"}
-   [**Virtual Environments, Packages, Import/Export**](Slides/02.EnvironmentPython.html){target="_blank"}
-   [**Basic Syntax, Typing, Indexing, Differences with R**](Slides/03.PythonRdifferences.html){target="_blank"}
-   [**Basics of Data Science: Intro to `NumPy` and `Pandas`**](Slides/10.NumpyPandas.html){target="_blank"}
-   [**Programming: Conditionals, Loops, Custom Functions**](Slides/20.Programming.html){target="_blank"}

### Exercises

*— The following exercises are fundamental, and they importantly integrate concepts from the slides and introduce new functions and methods that you want to know!*

-   [**First steps in Python** *(via Colab)*](https://colab.research.google.com/drive/1wp8LpzaO4wu-I6yhQS6uqD74h_739YWS){target="_blank"}
-   [**First steps with `NumPy` and `Pandas`** *(via Colab)*](https://colab.research.google.com/drive/1m3C52Ps-6g_PghzXEjtG2pr0pWFcB1EY){target="_blank"}
-   [**Basics of Programming... with some data science**](exercises/Exercises-Programming.html){target="_blank"}
-   [**Programming like a data scientist**](exercises/Exercises-LikeDataScientist.html){target="_blank"}
-   [<b>The data <em>nightmare</em> exercise... in Python</b>](exercises/Exercises-NightmarePy.html){target="_blank"}

*— These other exercises are beyond the scope of this introductory course, but they could be stimulating and useful as simple tutorials for some users:*

-   [**Basics of Clustering with K-Means and GMM**](exercises/Exercises-UnsupervClustering.html){target="_blank"}
    -   ::: {style="font-size:14px;"}
        **additional exercise on [Simulating clusters and assessing inferential risks](exercises/ExercisesExtra-SimulateClustering.html){target="_blank"}**
        :::
-   [<b>Basics of Sentiment Analysis with <em>HuggingFace</em> Transformers</b>](exercises/Exercises-SentimentAnalysis.html){target="_blank"}
-   [**Basics of Text Embeddings (plus PCA and Clustering)**](exercises/Exercises-EmbeddingsPCAClust.html){target="_blank"}
-   [**Basics of Text Classification using Embeddings and Cosine Similarity**](exercises/Exercises-EmbeddingsCosineSim.html){target="_blank"}
-   [**Other Examples of Language, Speech, and Image Processing**](exercises/Exercises-otherNLPexamples.html){target="_blank"}

------------------------------------------------------------------------

::: {style="font-size:11px;"}
GitHub repository associated to the present course website: [https://github.com/EnricoToffalini/Basics-Python](https://github.com/EnricoToffalini/Basics-Python){target="_blank"}
:::
